<a href="https://colab.research.google.com/github/JanetteFu/Message_Detect/blob/main/RNN_and_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv('/content/sample_data/clean_tweets_sentiment140_32k.csv')

In [ ]:
from sklearn.utils import shuffle
data = shuffle(data)
data = shuffle(data)
data['sentiment'] = data['sentiment'].replace(4,1)
data.head()

Unnamed: 0  ... sentiment
8160   8160        ...  0       
19006  1587006     ...  1       
12000  12000       ...  0       
14229  14229       ...  0       
26150  1594150     ...  1       

[5 rows x 5 columns]

In [ ]:
import re, nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
#from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
#stop_words = set(stopwords.words('english'))
wordnet_lemmatizer = WordNetLemmatizer()



def normalizer(tweet):
  tokens = nltk.word_tokenize(tweet)
  #filtered_result = list(filter(lambda l: l not in stop_words, tokens))
  lemmas = [wordnet_lemmatizer.lemmatize(t) for t in tokens]
  return lemmas

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
pd.set_option('display.max_colwidth', -1)
data['text'] = data.text.apply(str)
data['normalized_tweet'] = data.text.apply(normalizer)
data[['text', 'normalized_tweet']].head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  """Entry point for launching an IPython kernel.


text                                                                                      normalized_tweet
8160   i do not wanna go to school and find there fake friends i need an advice pleaseee  [i, do, not, wan, na, go, to, school, and, find, there, fake, friend, i, need, an, advice, pleaseee]
19006  danny your hair is awesomee is so talented your brave but i can see why            [danny, your, hair, is, awesomee, is, so, talented, your, brave, but, i, can, see, why]             
12000  love my boyfriend but so tired of explaining to people why he s never out with me  [love, my, boyfriend, but, so, tired, of, explaining, to, people, why, he, s, never, out, with, me] 
14229  rudely awakened by my bootlegged ll linden not happy                               [rudely, awakened, by, my, bootlegged, ll, linden, not, happy]                                      
26150  congratulations that s so exciting our engagement anniv is it will be years        [congratulation, that, s, so, exciting, our, engagement, anniv, is, it, will, be, year]

In [ ]:
data.head()

Unnamed: 0  ...                                                                                      normalized_tweet
8160   8160        ...  [i, do, not, wan, na, go, to, school, and, find, there, fake, friend, i, need, an, advice, pleaseee]
19006  1587006     ...  [danny, your, hair, is, awesomee, is, so, talented, your, brave, but, i, can, see, why]             
12000  12000       ...  [love, my, boyfriend, but, so, tired, of, explaining, to, people, why, he, s, never, out, with, me] 
14229  14229       ...  [rudely, awakened, by, my, bootlegged, ll, linden, not, happy]                                      
26150  1594150     ...  [congratulation, that, s, so, exciting, our, engagement, anniv, is, it, will, be, year]             

[5 rows x 6 columns]

In [ ]:
data = data.reset_index(drop=True)

In [ ]:
all_text1 = ' '.join(data['normalized_tweet'][0])
for i in range(1, len(data['normalized_tweet'])):
  temp = ' '.join(data['normalized_tweet'][i])
  all_text1 = all_text1+' '+temp

In [ ]:
data['normalized_tweet'][0:4]

0    [i, do, not, wan, na, go, to, school, and, find, there, fake, friend, i, need, an, advice, pleaseee]
1    [danny, your, hair, is, awesomee, is, so, talented, your, brave, but, i, can, see, why]             
2    [love, my, boyfriend, but, so, tired, of, explaining, to, people, why, he, s, never, out, with, me] 
3    [rudely, awakened, by, my, bootlegged, ll, linden, not, happy]                                      
Name: normalized_tweet, dtype: object

In [ ]:
all_text1[0:500]

'i do not wan na go to school and find there fake friend i need an advice pleaseee danny your hair is awesomee is so talented your brave but i can see why love my boyfriend but so tired of explaining to people why he s never out with me rudely awakened by my bootlegged ll linden not happy congratulation that s so exciting our engagement anniv is it will be year said i m not allowed to sign up for the baconlube beta ill so i cant go to the cinema i wish i had a tech guy feeling a bit better today '

In [ ]:
words = all_text1.split()

In [ ]:
from collections import Counter
## Build a dictionary that maps words to integers 
counts = Counter(words)

In [ ]:
vocab = sorted(counts, key=counts.get, reverse=True)
print(vocab)

['i', 'to', 'the', 'a', 'it', 'my', 'and', 'not', 'you', 'is', 'for', 'in', 's', 'of', 'on', 'that', 'have', 'me', 'so', 'm', 'but', 'just', 'day', 'do', 'at', 'be', 'with', 'wa', 'this', 'good', 'up', 'can', 'now', 'get', 'work', 'out', 'today', 'go', 'are', 'no', 'all', 'like', 'got', 'too', 'time', 'your', 'going', 'am', 'u', 'will', 'we', 'love', 'what', 'one', 'back', 'from', 'morning', 'know', 'about', 'some', 'lol', 'want', 'really', 'had', 'still', 'did', 'there', 'new', 'how', 'ha', '#', 'they', 'if', 'im', 'well', 'more', 'see', 'think', 'need', 'thanks', 'last', 'll', 'then', 'night', 'when', 'twitter', 'off', 'hope', 'home', 'an', 'he', 'oh', 'here', 'na', 'much', 're', 'been', 'again', 'great', 'make', 'feel', 'only', 'or', 'wish', 'why', 'would', 'miss', 'very', 'could', 'thing', 'haha', 'come', 'her', 'she', 'sleep', 'bad', 'school', 'week', 'by', 'sorry', 'way', 've', 'tomorrow', 'right', 'happy', 'sad', 'getting', 'nice', 'though', 'should', 'them', 'over', 'look', 'fr

In [ ]:
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

In [ ]:
vocab_to_int['railing']

11812

In [ ]:
tweet_ints = [] 
for i in range(0, len(data['normalized_tweet'])):
  temp = [vocab_to_int[word] for word in data['normalized_tweet'][i]]
  tweet_ints.append(temp)

In [ ]:
len(tweet_ints[31999])

2

In [ ]:
print('Unique words: ', len((vocab_to_int)))

Unique words:  23598


In [ ]:
import numpy as np

def pad_features(tweet_ints, seq_length):

# getting the correct rows x cols shape
  features = np.zeros((len(tweet_ints), seq_length), dtype=int)

# for each review, I grab that review and
  for i, row in enumerate(tweet_ints):
    features[i, -len(row):] = np.array(row)[:seq_length]
  return features
# Test your implementation!
seq_length=30
features = pad_features(tweet_ints, seq_length=30)

## test statements - do not change - ##
assert len(features)==len(tweet_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:10])

[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 156   4 232 137]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0  

In [ ]:
encoded_labels = list(data.sentiment)

In [ ]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(25600, 30) 
Validation set: 	(3200, 30) 
Test set: 		(3200, 30)


In [ ]:
import numpy
train_x = numpy.array(train_x)
train_y = numpy.array(train_y)
val_x = numpy.array(val_x)
val_y = numpy.array(val_y)
test_x = numpy.array(test_x)
test_y = numpy.array(test_y)

In [ ]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 50

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [ ]:
# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([50, 30])
Sample input: 
 tensor([[  0,   0,   0,  ...,  11, 165,   5],
        [  0,   0,   0,  ..., 161,  41, 627],
        [  0,   0,   0,  ..., 232,  44, 177],
        ...,
        [  0,   0,   0,  ..., 128, 249,  61],
        [  0,   0,   0,  ...,  95, 137, 667],
        [  0,   0,   0,  ..., 450,  56, 930]])

Sample label size:  torch.Size([50])
Sample label: 
 tensor([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        1, 0])


In [ ]:
# First checking if GPU is available
train_on_gpu=torch.cuda.is_available()
if(train_on_gpu):
  print('Training on GPU.')
else:
  print('No GPU available, training on CPU.')

Training on GPU.


In [ ]:
import torch.nn as nn

class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        # embedding and LSTM layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()
        

    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)

        # embeddings and lstm_out
        x = x.long()
        embeds = self.embedding(x)
        lstm_out, hidden = self.lstm(embeds, hidden)
    
        # stack up lstm outputs
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        # dropout and fully-connected layer
        out = self.dropout(lstm_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_(),
                      weight.new(self.n_layers, batch_size, self.hidden_dim).zero_())
        
        return hidden

In [ ]:
vocab_size = 23598
output_size = 2
embedding_dim = 30
hidden_dim = 128
n_layers = 1

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embedding): Embedding(23598, 30)
  (lstm): LSTM(30, 128, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=128, out_features=2, bias=True)
  (sig): Sigmoid()
)


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:50: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


In [ ]:
# loss and optimization functions
lr=0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [ ]:
# training params

epochs = 3 # 3-4 is approx where I noticed the validation loss stop decreasing

counter = 0
print_every = 100
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net.cuda()

net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)

    # batch loop
    for inputs, labels in train_loader:
        counter += 1

        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = tuple([each.data for each in h])

        # zero accumulated gradients
        net.zero_grad()

        # get the output from the model
        output, h = net(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = tuple([each.data for each in val_h])

                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())

                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/3... Step: 100... Loss: 0.697296... Val Loss: 0.663624
Epoch: 1/3... Step: 200... Loss: 0.663038... Val Loss: 0.645949
Epoch: 1/3... Step: 300... Loss: 0.650003... Val Loss: 0.634564
Epoch: 1/3... Step: 400... Loss: 0.682957... Val Loss: 0.632811
Epoch: 1/3... Step: 500... Loss: 0.532294... Val Loss: 0.613648
Epoch: 2/3... Step: 600... Loss: 0.597835... Val Loss: 0.603418
Epoch: 2/3... Step: 700... Loss: 0.588797... Val Loss: 0.585664
Epoch: 2/3... Step: 800... Loss: 0.604248... Val Loss: 0.575978
Epoch: 2/3... Step: 900... Loss: 0.448775... Val Loss: 0.568371
Epoch: 2/3... Step: 1000... Loss: 0.573688... Val Loss: 0.564184
Epoch: 3/3... Step: 1100... Loss: 0.676550... Val Loss: 0.553270
Epoch: 3/3... Step: 1200... Loss: 0.466880... Val Loss: 0.547172
Epoch: 3/3... Step: 1300... Loss: 0.511787... Val Loss: 0.546437
Epoch: 3/3... Step: 1400... Loss: 0.465144... Val Loss: 0.536856
Epoch: 3/3... Step: 1500... Loss: 0.535255... Val Loss: 0.535860


In [ ]:
#Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])

    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    #test_loss = criterion(output.squeeze(), labels.float())
    #test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))